### ISSUE TITLE
add a replicate mode for administration

### ISSUE THREAD

**Issue by jonenst** [100km/pointage100km#103]
We currently have
replicate init
replicate master
replicate slave
replicate checkpoint

None of these modes have bidirectional replication, no side-effects (automatic fixing of conflicts, sending of sms) and use filters that provide enough information for administration (we need data from all the sites).

So we need to add a new replicate mode for this purpose.

**Comment by samueltardieu** [comment]
`replicate mirror` has been introduced in 9816eaada4738739fa582a172d80224a78184d4c.
