### ISSUE TITLE
Change database name

### ISSUE THREAD

**Issue by samueltardieu** [100km/pointage100km#90]
Le nom steenwerck-N était déjà utilisé sur l'ancien système. On s'est retrouvé avec un PC en libre service qui tournait un vieux replicate sur une vieille copie de la base (steenwerck-13). On a eu du bol, il aurait pu réinjecter des vieilles informations en l'allumant.

Il faut qu'on trouve un nouveau schéma de nommage avec lequel cela ne risque pas d'arriver. Je propose "steenwerck-année-NN". Pour l'année prochaine, ça sera donc : "steenwerck-2016-1" pour la première base.

**Comment by jonenst** [comment]
+1

Jon

2015-05-15 14:40 GMT+02:00 Samuel Tardieu <notifications@github.com>:

**Comment by Tomo59** [comment]
Hmmmm, c'est bizarre, il me semblait que justement les noms ne devaient faire que s'incrémenter au fur et à mesure. Quand est-ce qu'on est repassé à 0 ?

La solution de ne faire qu'incrémenter me va bien aussi.

**Comment by samueltardieu** [comment]
Avant de passer à ce schéma là :) On commençait avec steenwerck, puis
steenwerck-2, etc., on le faisait à la main. C'est avant wipe.
