### ISSUE TITLE
Pointage et focus

### ISSUE THREAD

**Issue by samueltardieu** [100km/pointage100km#94]
Vérifier que le focus est systématiquement présent dans le champ de saisie des dossards sur les navigateurs usuels même lorsque le pointeur clique sur un concurrent pour avoir ses détails.

**Comment by samueltardieu** [comment]
Je crois que c'est @jonenst qui avait remarqué quelque chose de bizarre. Tu peux vérifier ?

**Comment by jonenst** [comment]
Le keypad envoie (ev.which dans firefox et chrome) 97 pour "KP_1" et 49 pour "1".
firefox préconise (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) ev.key avec comme valeurs "1" dans les deux cas, et "ArrowDown" et "ArrowUp"
chrome utilise autre chose...
Et IE  ? :)

**Comment by Tomo59** [comment]
Pour info, l'event dans Chrome...

KeyboardEvent {isTrusted: true}
altKey: false
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "Numpad1"
ctrlKey: false
currentTarget: null
defaultPrevented: true
detail: 0
eventPhase: 0
isTrusted: true
isTrusted: true
keyCode: 97
keyIdentifier: "U+0041"
keyLocation: 3
location: 3
metaKey: false
path: Array[4]
repeat: false
returnValue: false
shiftKey: false
sourceCapabilities: InputDeviceCapabilities
srcElement: body
target: body
timeStamp: 1457044813560
type: "keyup"
view: Window
which: 97

**Comment by Tomo59** [comment]
Bien sûr pas de champ "key" pour chrome, c'eut été trop beau !

**Comment by samueltardieu** [comment]
C'est corrigé, c'est ça ?

**Comment by Tomo59** [comment]
Fixed in fc5e137d5817ad199b3344b86e97fda4166845b6
